steps:
- task: Maven@3
  displayName: 'Maven $(mavenPOMFile)'
  inputs:
    mavenPomFile: Application/pom.xml
    testResultsFiles: '**/TEST*.xml'

- task: CopyFiles@2
  displayName: 'Copy functional test jar to: $(TargetFolder)'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**/*jar-with-dependencies.jar'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    flattenFolders: true

- task: Docker@1
  displayName: 'Build an image'
  inputs:
    azureSubscriptionEndpoint: 'vintomdevops - Azure'
    azureContainerRegistry: vintomdevopsacr.azurecr.io
    imageName: 'vintomdevops:$(Build.BuildId)'

- task: Docker@1
  displayName: 'Push an image'
  inputs:
    azureSubscriptionEndpoint: 'vintomdevops - Azure'
    azureContainerRegistry: vintomdevopsacr.azurecr.io
    command: 'Push an image'
    imageName: 'vintomdevops:$(Build.BuildId)'